spring.application.name=campuscore
spring.datasource.url=jdbc:postgresql://localhost:5432/campuscore
spring.datasource.username=postgres
spring.datasource.password=8M98ppqs
spring.jpa.hibernate.ddl-auto=update
